export const FIND_RESULTS = 'findResults'
export const FIND_SUGGESTIONS = 'findSuggestions'
export const FIND_CURRENT_ITEM = 'findCurrentItem'
export const FIND_CURRENT_ITEM_STOCK = 'getCurrentItemStock'
export const UPDATE_CURRENT_ITEM_STOCK = 'updateCurrentItemStock'
export const CREATE_PRODUCT = 'createProduct'
export const DELETE_PRODUCT = 'deleteProduct'